#!/bin/bash

tsc
npm run typedoc

REFS="$PWD/../rsvim.github.io/docs/api_references"
GLOBAL="$PWD/../rsvim.github.io/docs/api_references/10__global"
RSVIM="$PWD/../rsvim.github.io/docs/api_references/50__rsvim"

if [ -d $GLOBAL ]; then
	rm -rf $GLOBAL
fi
if [ -d $RSVIM ]; then
	rm -rf $RSVIM
fi

mv ./generated-typedocs/10__global $REFS
mv ./generated-typedocs/50__rsvim $REFS
