declare function checkNotNull(arg: any, msg: string): void;
declare function checkIsNumber(arg: any, msg: string): void;
declare function checkIsInteger(arg: any, msg: string): void;
declare function checkIsBoolean(arg: any, msg: string): void;
declare function checkIsFunction(arg: any, msg: string): void;
declare function checkIsOptions(arg: any, options: any[], msg: string): void;
declare function boundByIntegers(arg: any, bound: [number, number]): any;
declare function clearInterval(id: number): void;
declare function clearTimeout(id: number): void;
declare function queueMicrotask(callback: () => void): void;
declare function reportError(error: any): void;
declare function setInterval(callback: (...args: any[]) => void, delay?: number, ...args: any[]): number;
declare function setTimeout(callback: (...args: any[]) => void, delay?: number, ...args: any[]): number;
