//! Prelude.

pub use crate::arc_mutex_ptr;
pub use crate::arc_ptr;
pub use crate::consts::*;
pub use crate::coord::*;
pub use crate::err::*;
pub use crate::lock;
pub use crate::point;
pub use crate::point_as;
pub use crate::rc_ptr;
pub use crate::rc_refcell_ptr;
pub use crate::rect;
pub use crate::rect_as;
pub use crate::rect_from_layout;
pub use crate::rect_from_size;
pub use crate::size;
pub use crate::size_as;
pub use crate::util::ringbuf::DeRingBuffer;
pub use crate::util::ringbuf::RingBuffer;
pub use foldhash::HashMap as FoldMap;
pub use foldhash::HashMapExt;
pub use foldhash::HashSet as FoldSet;
pub use foldhash::HashSetExt;
pub use foldhash::fast::RandomState;
pub use log::debug;
pub use log::error;
pub use log::info;
pub use log::trace;
pub use log::warn;
pub use std::collections::BTreeMap;
pub use std::collections::BTreeSet;
pub use std::path::Path;
pub use std::path::PathBuf;
