allow-branch = ["main"]
shared-version = true
tag = false
pre-release-hook = [
  "git-cliff",
  "-o",
  "RSVIM_CORE_CHANGELOG.md",
  "--tag",
  "{{version}}",
]
tag-message = "chore(release): {{version}}"
