name: Cargo Miri
permissions:
  contents: write
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 3
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  RUST_BACKTRACE: "full"
  RUSTUP_MAX_RETRIES: 3
  GH_TOKEN: ${{ github.token }}
  TESTS_LIST: ".tests_list.txt"
defaults:
  run:
    shell: bash
jobs:
  group:
    name: (Experimental) Cargo Miri
    runs-on: ubuntu-22.04
    outputs:
      total_tests: ${{ steps.group_all_tests.outputs.total_tests }}
      tests_per_group: ${{ steps.group_all_tests.outputs.tests_per_group }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: Group all tests
        id: group_all_tests
        env:
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
        run: |
          cargo +nightly nextest list >$TESTS_LIST
          sed -i 1d $TESTS_LIST
          total_tests=$(wc -l <"$TESTS_LIST")
          tests_per_group=$((total_tests/10))
          echo "total_tests:$total_tests, tests_per_group:$tests_per_group"
          echo "total_tests=$total_tests" >> $GITHUB_OUTPUT
          echo "tests_per_group=$tests_per_group" >> $GITHUB_OUTPUT
  miri0:
    name: (Experimental) Cargo Miri-0
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          cat $TESTS_LIST | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri1:
    name: (Experimental) Cargo Miri-1
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP))
          cat $TESTS_LIST | tail -n $skip_line | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri2:
    name: (Experimental) Cargo Miri-2
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP*2))
          cat $TESTS_LIST | tail -n $skip_line | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri3:
    name: (Experimental) Cargo Miri-3
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP*3))
          cat $TESTS_LIST | tail -n $skip_line | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri4:
    name: (Experimental) Cargo Miri-4
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP*4))
          cat $TESTS_LIST | tail -n $skip_line | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri5:
    name: (Experimental) Cargo Miri-5
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP*5))
          cat $TESTS_LIST | tail -n $skip_line | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri6:
    name: (Experimental) Cargo Miri-6
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP*6))
          cat $TESTS_LIST | tail -n $skip_line | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri7:
    name: (Experimental) Cargo Miri-7
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP*7))
          cat $TESTS_LIST | tail -n $skip_line | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri8:
    name: (Experimental) Cargo Miri-8
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP*8))
          cat $TESTS_LIST | tail -n $skip_line | head -n $TESTS_PER_GROUP | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
  miri9:
    name: (Experimental) Cargo Miri-9
    runs-on: ubuntu-22.04
    needs: group
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
          TOTAL_TESTS: ${{ needs.group.outputs.total_tests }}
          TESTS_PER_GROUP: ${{ needs.group.outputs.tests_per_group }}
        run: |
          skip_line=$((TOTAL_TESTS-TESTS_PER_GROUP*9))
          cat $TESTS_LIST | tail -n $skip_line | xargs -I {} cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features {}
