name: Cargo Miri
permissions:
  contents: write
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 3
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  RUST_BACKTRACE: "full"
  RUSTUP_MAX_RETRIES: 3
  GH_TOKEN: ${{ github.token }}
defaults:
  run:
    shell: bash
jobs:
  miri:
    name: (Experimental) Cargo Miri
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: taiki-e/install-action@cargo-nextest
      - name: miri
        env:
          MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-permissive-provenance"
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
        run: |
          cargo +nightly miri nextest run -p rsvim_core -F unicode_lines --no-default-features
