name: (Experimental) CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 3
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  RUST_BACKTRACE: "full"
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: crate-ci/typos@master
      - name: Prettier
        run: |
          npm install -g prettier
          prettier --version
          echo "show PWD=${PWD}"
          echo "prettier --check *.md **/*.ts"
          prettier --check *.md **/*.ts
  build:
    name: Nightly Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: [beta, nightly]
    env:
      RUSTC_WRAPPER: "sccache"
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
      - uses: actions/checkout@v4
      - name: Build Release
        run: |
          cargo build --release
          ./target/release/rsvim --version
      - name: Build Debug
        run: |
          cargo build
          ./target/debug/rsvim --version
